services:
  app:
    build:
      context: .
      dockerfile: docker/php/Dockerfile
    container_name: laravel12-octane-app
    ports:
      - "8000:8000"
    working_dir: /var/www
    volumes:
      - ./backend:/var/www
    depends_on:
      - db
  
  db:
    image: postgres:latest
    container_name: laravel12-octane-db
    environment:
      POSTGRES_DB: laravel
      POSTGRES_USER: laravel
      POSTGRES_PASSWORD: secret
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./docker/postgres/postgresql.conf:/etc/postgresql/postgresql.conf
    command: postgres -c config_file=/etc/postgresql/postgresql.conf

  node:
    build:
      context: ./docker/node
    container_name: node
    working_dir: /var/www
    volumes:
      - ./backend:/var/www
    command: tail -f /dev/null

  valkey:
    build:
      context: .
      dockerfile: docker/valkey/Dockerfile
    container_name: valkey
    ports:
      - "6379:6379"
    volumes:
      - valkey-data:/data
      - ./docker/valkey/valkey.conf:/etc/valkey/valkey.conf
    restart: unless-stopped

volumes:
  pgdata:
  valkey-data: